/**
 * The service's contract, generated from service/orrery_service/contract.py.
 *
 * Do not edit this file. Change the Pydantic models and run
 *
 *     python service/tools/export_contract.py
 *
 * Continuous integration runs the same command and fails if what it writes
 * differs from what is committed, so the two halves of the boundary cannot
 * describe different things.
 */

export type JobState = 'queued' | 'running' | 'done' | 'failed';

/**
 * One reason a submission was refused.
 *
 * The shape the C++ already reports in: the setting named in the spelling the
 * file uses, and what is wrong with it. `orrery run` prints exactly this pair
 * for every objection at once, and so does this, for the same reason
 * `configuration.hpp` gives: somebody who has written three mistakes should be
 * told about three mistakes rather than discover them one submission at a
 * time.
 */
export interface Problem {
  /** The setting, as section.key. */
  readonly setting: string;
  /** What is wrong with it. */
  readonly complaint: string;
}

/** Everything wrong with a submission, in the order the settings appear. */
export interface Rejection {
  readonly problems: readonly Problem[];
}

/**
 * What the service will accept, so the client can say so before submitting.
 *
 * Sent rather than compiled into the client, so that a service raising or
 * lowering a ceiling does not need the site rebuilt to stop offering runs it
 * will refuse. `orrery_service/limits.py` is where the numbers and their
 * reasons live.
 */
export interface Limits {
  readonly max_particles: number;
  readonly max_steps: number;
  /** Particle count times its logarithm times steps, at most. */
  readonly max_work: number;
  readonly max_queue: number;
  /** The solver kinds a submission may name. */
  readonly solvers: readonly string[];
}

/**
 * What this service has actually achieved, for pricing a run.
 *
 * Not a figure from `docs/performance.md`. Those were measured on the laptop
 * the reports name, and the machine a container lands on is not that laptop,
 * so quoting them here would attribute this service's speed to hardware it
 * does not have. This is the median over jobs this service has completed, and
 * `jobs` says how many, so a client can decline to price anything from one
 * sample.
 *
 * Absent until something has run. A client with no reference says the estimate
 * is not available rather than showing a number nothing measured.
 */
export interface Reference {
  /** Median milliseconds a step. */
  readonly step_ms: number;
  /** The particle count that median was taken at. */
  readonly particles: number;
  /** Completed runs the median is over. */
  readonly jobs: number;
}

/**
 * What the service can do at the moment it was asked.
 *
 * Fetched before the console offers to submit anything. Several conditions
 * each independently mean the button should say something other than "submit":
 * no worker has beaten recently, the queue is full, the service has spent the
 * computing it allows itself in a day, or it did not answer at all. ADR-0054 is
 * what the client does in each case.
 *
 * Which of them it is arrives as a sentence rather than as flags the client
 * turns back into one. The service knows why it is refusing, and a client
 * reconstructing the reason from `workers` and `queued` would be a second
 * statement of the same rule that quietly stops matching the first the moment a
 * new condition is added, which is what happened when the budget was.
 */
export interface Capabilities {
  /** The simulator version the worker runs. */
  readonly version: string;
  readonly limits: Limits;
  /** False when no worker is alive, the queue is full, or the service has spent its budget for the day. */
  readonly accepting: boolean;
  /** Empty while accepting. Otherwise one sentence saying which of those it is, in the service's own words. */
  readonly refusal: string;
  readonly queued: number;
  readonly workers: number;
  readonly reference: Reference | null;
}

/**
 * A run somebody wants taken.
 *
 * One field. Everything about the run is in the configuration, which is the
 * property `configuration.hpp` exists to provide: a configuration file plus a
 * revision of this repository determines the trajectory.
 */
export interface Submission {
  /** The text of an .orrery file. */
  readonly configuration: string;
}

/**
 * How far a run has got.
 *
 * Every field is measured by the worker from the run's own output rather than
 * estimated: the step and the time are read from what the simulator prints,
 * the step time is wall clock divided by steps taken since the last report,
 * and the energy drift is the last row of the diagnostics file the run is
 * writing. A progress bar that interpolates is a progress bar that lies when a
 * run slows down.
 */
export interface Progress {
  readonly step: number;
  /** Model time, in the configuration's units. */
  readonly time: number;
  readonly step_ms: number | null;
  readonly energy_drift: number | null;
}

/**
 * A submitted run, at whatever stage it has reached.
 *
 * The same shape whether it is read once by polling or pushed repeatedly over
 * a WebSocket, so that a client falling back from one to the other changes how
 * often it learns things and not what it learns. That is the whole of why the
 * socket carries this and not a smaller update message.
 */
export interface Job {
  readonly id: string;
  readonly state: JobState;
  readonly created: string;
  readonly position: number | null;
  readonly attempts: number;
  readonly particles: number;
  readonly steps: number;
  readonly timestep: number;
  readonly stride: number;
  readonly frames: number;
  readonly progress: Progress;
  readonly error: string;
  readonly trajectory: string | null;
  readonly diagnostics: string | null;
}

/**
 * The answer to a submission.
 *
 * Carries the whole job rather than only its identifier, because the client's
 * next question is always "where am I in the queue" and answering it in the
 * same response saves a round trip on the one request a person is watching.
 *
 * `duplicate` is true when the configuration had already been submitted and
 * this is the earlier job. Jobs are idempotent by the hash of the
 * configuration they run, so submitting the same document twice returns the
 * first result rather than running it again, and the client says so rather
 * than appearing to have queued something that never moves.
 */
export interface Accepted {
  readonly job: Job;
  readonly duplicate: boolean;
}

/**
 * Whether the process is alive, and whether it can do its work.
 *
 * Two questions rather than one. A process that is running but cannot reach
 * the database should be restarted rather than sent traffic, and an
 * orchestrator can only tell those apart if the answers are separate fields.
 */
export interface Health {
  readonly alive: boolean;
  readonly ready: boolean;
  readonly detail: string;
}
