// @vitest-environment node

/**
 * A design out of the editor, run natively and run here.
 *
 * This is the test the editor exists to pass. The claim it makes is that a
 * design leaves as a configuration the native binary runs unmodified and gives
 * the run the editor previewed, and there are three things in that claim: the
 * file the editor writes is one the C++ accepts, the sample it produces is where
 * the drawing said it would be, and the browser and the native build agree about
 * what happens next.
 *
 * The fixtures are one native run of the file this test writes:
 *
 *     ORRERY_WRITE_FIXTURES=1 npx vitest run tests/editor/agreement.test.ts
 *     orrery run tests/fixtures/editor.orrery \
 *         --set output.trajectory_path=tests/fixtures/editor.otj \
 *         --set output.trajectory_stride=200 \
 *         --set output.diagnostics_path=tests/fixtures/editor.csv \
 *         --set output.diagnostics_stride=200
 *
 * The two strides are overridden because the file asks for a frame a step, which
 * is right for a run somebody wants to watch and forty times more trajectory
 * than a test should commit. Neither the sample nor the integration depends on
 * them.
 *
 * They are committed, against the rule that output is not, for the reason the
 * trajectory reader's fixtures are: they are the only thing that says the two
 * builds agree, and a test whose input has to be regenerated by a toolchain
 * nobody installed to work on the client is a test that stops being run.
 *
 * ## What the two builds can and cannot be held to
 *
 * The disc is compared particle for particle. The bulge is not, and the reason
 * is worth stating rather than working around: the two builds draw different
 * bulges from the same seed. The divergence begins exactly at the first bulge
 * particle, and the bulge is drawn by `make_plummer_sphere`, whose per-particle
 * statement passes two draws from the random stream as two arguments of one
 * call. C++ leaves the order of argument evaluation unspecified, so two
 * compilers may take the position's direction and the velocity's direction in
 * opposite orders, which gives the same distribution and a different sample.
 * Every draw the disc makes is its own statement, and the disc agrees exactly.
 *
 * The disc's heights are drawn the same way and diverge for the same reason:
 * `make_disc_galaxy` draws the height and its sign as the two operands of a
 * multiplication, which C++ also leaves unsequenced. A particle's radius and
 * angle come from statements of their own and agree exactly, which is why the
 * disc can still be compared in x.
 *
 * That is a defect in the sampler rather than in anything this phase built, and
 * it is left alone here: hoisting those two calls into named locals would change
 * every Plummer sample this repository has ever published, including the runs in
 * the gallery and the figures in the reports. So what is compared past the
 * sample is what does not depend on which bulge was drawn: where each galaxy is
 * after two hundred steps, and that both builds conserve energy to the same
 * order over the run.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { parseDiagnostics } from '../../src/diagnostics/series';
import { describeDesign } from '../../src/editor/description';
import { writeDesign } from '../../src/editor/design';
import {
  components,
  encounterOf,
  norm,
  primaryCount,
  primaryGalaxy,
  secondaryGalaxy,
  separationVector,
  totalMass,
} from '../../src/editor/elements';
import {
  lastError,
  loadOrrery,
  MEASUREMENT,
  MEASUREMENT_COUNT,
  type OrreryModule,
  putString,
} from '../../src/solver/module';
import {
  decodeFrame,
  frameCount,
  frameOffset,
  parseHeader,
} from '../../src/trajectory/format';
import { FIXTURE_DESIGN } from './fixture';

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURES = join(HERE, '..', 'fixtures');
const PUBLIC = join(HERE, '..', '..', 'public');

/** What `loadOrrery` resolves `solver/orrery.js` against, as a file URL. */
const BASE = `file:///${PUBLIC.replaceAll('\\', '/')}/`;

const CONFIGURATION = join(FIXTURES, 'editor.orrery');
const TRAJECTORY = join(FIXTURES, 'editor.otj');

const text = writeDesign(FIXTURE_DESIGN, describeDesign);
if (process.env.ORRERY_WRITE_FIXTURES === '1') {
  writeFileSync(CONFIGURATION, text, 'utf8');
}

const built = existsSync(join(PUBLIC, 'solver', 'orrery.js'));
if (!built) {
  console.warn(
    'the solver module is not built, so the editor round trip is skipped.\n' +
      'Build it with: cmake --preset wasm && cmake --build --preset wasm',
  );
}

/** Positions are floats by the time anything reads them, so this is their limit. */
const FLOAT_TOLERANCE = 2e-6;

/**
 * How closely a sampled centre of mass has to sit where the placement says.
 *
 * Not a tolerance on the arithmetic: the two galaxies are recentred to
 * round-off before they are separated, so the sampled separation is the exact
 * one to within the accumulated error of summing a few thousand single-precision
 * positions. A part in a hundred thousand of a separation of twenty is
 * comfortably inside that and far outside anything a wrong formula would give.
 */
const PLACEMENT_TOLERANCE = 2e-4;

interface Frame {
  readonly x: Float32Array;
  readonly y: Float32Array;
  readonly z: Float32Array;
  readonly step: number;
}

function frameAt(native: Uint8Array, index: number): Frame {
  const header = parseHeader(native);
  const into = {
    x: new Float32Array(header.count),
    y: new Float32Array(header.count),
    z: new Float32Array(header.count),
  };
  const frame = decodeFrame(native, frameOffset(index, header), header, into);
  return { ...into, step: frame.step };
}

/** The mean position of a range of particles, which for equal masses is their centre of mass. */
function centre(frame: Frame, from: number, to: number): [number, number, number] {
  let x = 0;
  let y = 0;
  let z = 0;
  for (let index = from; index < to; index += 1) {
    x += frame.x[index] as number;
    y += frame.y[index] as number;
    z += frame.z[index] as number;
  }
  const count = to - from;
  return [x / count, y / count, z / count];
}

describe('a design out of the editor', () => {
  it('is the configuration committed beside this test', () => {
    // The fixture is the editor's own output. If this fails, the writer has been
    // changed and the native run beside it is a run of a different file, so both
    // are regenerated together by the commands at the top of this file.
    expect(readFileSync(CONFIGURATION, 'utf8').replace(/\r\n/g, '\n')).toBe(text);
  });

  it('states in its header only what its settings come to', () => {
    const encounter = encounterOf(FIXTURE_DESIGN);
    expect(text).toContain(`periapsis          ${encounter.periapsis.toFixed(3)}`);
    expect(text).toContain('orrery run collision-20260814.orrery');
    // The pair is bound, and the header says so in words rather than leaving the
    // sign of the energy to be read.
    expect(encounter.bound).toBe(true);
    expect(text).toContain('bound');
  });
});

/** The committed native run, read when a test wants it rather than at collection. */
function nativeRun(): Uint8Array {
  return new Uint8Array(readFileSync(TRAJECTORY));
}

describe.runIf(existsSync(TRAJECTORY))('the native run of it', () => {
  it('samples the particle count the design asked for', () => {
    expect(parseHeader(nativeRun()).count).toBe(FIXTURE_DESIGN.count);
  });

  it('puts the two galaxies where the drawing puts them', () => {
    const native = nativeRun();
    const header = parseHeader(native);
    // The elements the editor shows are a transcription of the C++ that samples
    // the design. This is the check on that transcription: where the sampler
    // actually put the two galaxies, measured from its own output, against where
    // `elements.ts` says they are.
    const first = frameAt(native, 0);
    expect(first.step).toBe(0);

    const split = primaryCount(FIXTURE_DESIGN);
    const primary = centre(first, 0, split);
    const secondary = centre(first, split, header.count);

    const separation = separationVector(FIXTURE_DESIGN);
    const measured = {
      x: secondary[0] - primary[0],
      y: secondary[1] - primary[1],
      z: secondary[2] - primary[2],
    };

    expect(measured.x).toBeCloseTo(separation.x, 3);
    expect(measured.y).toBeCloseTo(separation.y, 3);
    expect(measured.z).toBeCloseTo(separation.z, 3);
    expect(Math.abs(norm(measured) - norm(separation)) / norm(separation)).toBeLessThan(
      PLACEMENT_TOLERANCE,
    );

    // And the pair is in its own centre-of-mass frame, which is what makes the
    // two shares of the separation the drawing splits it into the right ones.
    const massPrimary = totalMass(primaryGalaxy(FIXTURE_DESIGN));
    const massSecondary = totalMass(secondaryGalaxy(FIXTURE_DESIGN));
    const total = massPrimary + massSecondary;
    const barycentre =
      (primary[0] * massPrimary + secondary[0] * massSecondary) / total;
    expect(Math.abs(barycentre)).toBeLessThan(PLACEMENT_TOLERANCE * norm(separation));
  });
});

describe.runIf(built && existsSync(TRAJECTORY))('the browser run of it', () => {
  /**
   * Read the module's positions into arrays of its own.
   *
   * The module hands back views onto its heap, and the heap is replaced whenever
   * it grows, so what a comparison holds has to be a copy.
   */
  function positionsOf(module: OrreryModule, handle: number): Frame {
    const count = module._orrery_particle_count(handle);
    const pointer = module._malloc(3 * count * 4);
    if (module._orrery_read_positions(handle, pointer) === 0) {
      throw new Error(lastError(module));
    }
    const floats = pointer / 4;
    const frame: Frame = {
      x: new Float32Array(module.HEAPF32.subarray(floats, floats + count)),
      y: new Float32Array(module.HEAPF32.subarray(floats + count, floats + 2 * count)),
      z: new Float32Array(
        module.HEAPF32.subarray(floats + 2 * count, floats + 3 * count),
      ),
      step: module._orrery_step_index(handle),
    };
    module._free(pointer);
    return frame;
  }

  it('samples the same disc as the native build did', async () => {
    const native = frameAt(nativeRun(), 0);
    const module = await loadOrrery(BASE);

    const pointer = putString(module, text);
    const handle = module._orrery_create(pointer);
    module._free(pointer);
    if (handle === 0) throw new Error(lastError(module));

    const sampled = positionsOf(module, handle);
    expect(sampled.step).toBe(0);

    // The primary's disc, particle for particle, in the one coordinate the two
    // builds can be held to. The sampler documents its own ordering, so this is
    // a comparison of two draws from the same stream rather than of two clouds
    // that happen to look alike.
    //
    // x rather than all three because of the second unsequenced expression named
    // at the top of this file: the disc's heights are drawn by a statement whose
    // two draws are the operands of a multiplication, so the two builds give a
    // particle the same radius and the same angle and a different height. This
    // fixture's discs have no position angle and are tilted about the x axis, so
    // x is the coordinate a height cannot reach, and it agrees exactly.
    expect(FIXTURE_DESIGN.positionAngle).toBe(0);
    const disc = components(primaryGalaxy(FIXTURE_DESIGN)).discCount;
    expect(disc).toBeGreaterThan(100);
    for (let index = 0; index < disc; index += 1) {
      expect(sampled.x[index] as number).toBeCloseTo(native.x[index] as number, 5);
    }

    module._orrery_destroy(handle);
  });

  it('agrees where the two galaxies are two hundred steps later', async () => {
    const native = nativeRun();
    const header = parseHeader(native);
    const last = frameAt(native, frameCount(native.byteLength, header) - 1);
    expect(last.step).toBe(FIXTURE_DESIGN.steps);

    const module = await loadOrrery(BASE);
    const pointer = putString(module, text);
    const handle = module._orrery_create(pointer);
    module._free(pointer);
    if (handle === 0) throw new Error(lastError(module));

    const measurement = module._malloc(MEASUREMENT_COUNT * 8);
    module._orrery_measure(handle, measurement);

    let taken = 0;
    while (taken < FIXTURE_DESIGN.steps) {
      const advanced = module._orrery_advance(handle, FIXTURE_DESIGN.steps - taken);
      if (advanced === 0) throw new Error(lastError(module));
      taken += advanced;
    }
    if (module._orrery_measure(handle, measurement) === 0) {
      throw new Error(lastError(module));
    }

    const stepped = positionsOf(module, handle);
    expect(stepped.x.length).toBe(header.count);

    const split = primaryCount(FIXTURE_DESIGN);
    for (const [from, to] of [
      [0, split],
      [split, header.count],
    ] as const) {
      const here = centre(stepped, from, to);
      const there = centre(last, from, to);
      for (let axis = 0; axis < 3; axis += 1) {
        expect(here[axis] as number).toBeCloseTo(there[axis] as number, 3);
      }
    }

    // Something has to have moved, or the comparison above is between two
    // copies of the state the run started in.
    expect(Math.max(...[...stepped.x].map(Math.abs))).toBeGreaterThan(FLOAT_TOLERANCE);

    const drift = module.HEAPF64[measurement / 8 + MEASUREMENT.energyDrift] as number;
    const diagnostics = parseDiagnostics(
      readFileSync(join(FIXTURES, 'editor.csv'), 'utf8'),
    );
    const nativeDrift = diagnostics.energyDrift[diagnostics.samples - 1] as number;

    // Both builds conserve energy to the same order over the same run. Not to
    // the same digits: the energy error is a difference between two nearly equal
    // energies, and the two samples are not the same sample.
    expect(Math.abs(drift)).toBeLessThan(1e-3);
    expect(Math.abs(nativeDrift)).toBeLessThan(1e-3);

    module._free(measurement);
    module._orrery_destroy(handle);
  });
});
