// @vitest-environment node

/**
 * The WebAssembly build against the native build, on the same run.
 *
 * This is the test the whole module exists to pass. Compiling the solver rather
 * than reimplementing it is only worth anything if the compiled one gives the
 * same answers, and the only way to know that is to run the same configuration
 * both ways and compare.
 *
 * The fixtures are one native run of `web/tests/fixtures/agreement.orrery`:
 *
 *     orrery run web/tests/fixtures/agreement.orrery
 *
 * which writes the trajectory and the diagnostics beside it. They are committed,
 * against the rule that output is not, for the reason the trajectory reader's
 * fixtures are: they are the only thing that says the two builds agree, and a
 * test whose input has to be regenerated by a toolchain nobody installed to work
 * on the client is a test that stops being run.
 *
 * ## The two comparisons are at different precisions, on purpose
 *
 * The conserved quantities cross the boundary as doubles and are compared as
 * doubles, which is where the numerical claim is made. The positions cross as
 * floats, because what reads them is a renderer, and are therefore compared only
 * to what a float can hold. Widening that path to double for the sake of a test
 * would double what every frame costs to move for the length of every run.
 *
 * ## Why the two are not required to agree bit for bit
 *
 * The native build runs the AVX2 kernel and the WebAssembly build has no vector
 * kernel at all, so the sums are accumulated in a different order and one of
 * them uses fused multiply-add. `solvers/direct_kernel.hpp` sets out exactly
 * what that is allowed to change, and ADR-0020 why. The two builds also reach
 * different implementations of the standard maths library, which is where the
 * initial conditions come from: `core/random.hpp` promises a sampled
 * configuration exactly within a platform and to a few units in the last place
 * across them.
 *
 * On the machine this was written on the two agree far more closely than the
 * tolerances below: the conserved quantities to the last bit or two, and the
 * positions to what a float can hold. The tolerances are loose because the
 * fixture was written by one platform's maths library and the module under test
 * may have been built by another's, and the energy error in particular is a
 * difference between two nearly equal energies and so magnifies a last-bit
 * difference by about eight orders of magnitude.
 */

import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { parseDiagnostics } from '../../src/diagnostics/series';
import {
  lastError,
  loadOrrery,
  MEASUREMENT,
  MEASUREMENT_COUNT,
  type OrreryModule,
  putString,
} from '../../src/solver/module';
import {
  decodeFrame,
  frameCount,
  frameOffset,
  parseHeader,
} from '../../src/trajectory/format';

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURES = join(HERE, '..', 'fixtures');
const PUBLIC = join(HERE, '..', '..', 'public');
const SOLVER = join(PUBLIC, 'solver');

/** What `loadOrrery` resolves `solver/orrery.js` against, as a file URL. */
const BASE = `file:///${PUBLIC.replaceAll('\\', '/')}/`;

/**
 * The module is compiler output and a checkout that has never run the wasm
 * preset does not have it.
 *
 * Skipped rather than failed in that case, and skipped loudly, which is the
 * arrangement the Python bindings' suite already uses for the same situation.
 * Continuous integration builds the module before it runs this, so the skip is
 * never taken there and a broken module cannot pass unnoticed.
 */
const built = existsSync(join(SOLVER, 'orrery.js'));
if (!built) {
  console.warn(
    'the solver module is not built, so the agreement test is skipped.\n' +
      'Build it with: cmake --preset wasm && cmake --build --preset wasm',
  );
}

/**
 * What a quantity measured in double precision has to agree to.
 *
 * A part in a thousand million. Measured here at a part in 10^16, which is the
 * last bit; the gap is the margin described at the top of this file.
 */
const TOLERANCE = 1e-9;

/**
 * What the energy error has to agree to, which is looser and has to be.
 *
 * It is the difference between two energies that agree to fifteen digits,
 * divided by one of them, so a difference in the last bit of either moves it by
 * a part in ten thousand. Measured here at zero.
 */
const DRIFT_TOLERANCE = 1e-4;

/** What a float can hold, which is what the positions crossed the boundary as. */
const FLOAT_TOLERANCE = 2e-6;

function text(name: string): string {
  return readFileSync(join(FIXTURES, name), 'utf8');
}

interface Result {
  readonly count: number;
  readonly step: number;
  readonly time: number;
  readonly x: Float32Array;
  readonly y: Float32Array;
  readonly z: Float32Array;
  readonly measurement: Float64Array;
  readonly solver: string;
  readonly kernel: string;
  readonly report: string;
}

/** Run the configuration in the module and read everything back. */
function integrate(module: OrreryModule, configuration: string, steps: number): Result {
  const pointer = putString(module, configuration);
  const handle = module._orrery_create(pointer);
  module._free(pointer);
  if (handle === 0) throw new Error(lastError(module));

  // The first measurement fixes what the energy error is relative to, exactly
  // as the first row of a diagnostics file does.
  const measurement = module._malloc(MEASUREMENT_COUNT * 8);
  module._orrery_measure(handle, measurement);

  let taken = 0;
  while (taken < steps) {
    const advanced = module._orrery_advance(handle, steps - taken);
    if (advanced === 0) throw new Error(lastError(module));
    taken += advanced;
  }

  const count = module._orrery_particle_count(handle);
  const positions = module._malloc(3 * count * 4);
  if (module._orrery_read_positions(handle, positions) === 0) {
    throw new Error(lastError(module));
  }
  if (module._orrery_measure(handle, measurement) === 0) {
    throw new Error(lastError(module));
  }

  const floats = positions / 4;
  const doubles = measurement / 8;
  const result: Result = {
    count,
    step: module._orrery_step_index(handle),
    time: module._orrery_time(handle),
    x: new Float32Array(module.HEAPF32.subarray(floats, floats + count)),
    y: new Float32Array(module.HEAPF32.subarray(floats + count, floats + 2 * count)),
    z: new Float32Array(
      module.HEAPF32.subarray(floats + 2 * count, floats + 3 * count),
    ),
    measurement: new Float64Array(
      module.HEAPF64.subarray(doubles, doubles + MEASUREMENT_COUNT),
    ),
    solver: module.UTF8ToString(module._orrery_solver_name(handle)),
    kernel: module.UTF8ToString(module._orrery_kernel_name(handle)),
    report: module.UTF8ToString(module._orrery_report(handle)),
  };

  module._free(positions);
  module._free(measurement);
  module._orrery_destroy(handle);
  return result;
}

describe.skipIf(!built)('the WebAssembly build', () => {
  const configuration = text('agreement.orrery');
  const native = new Uint8Array(readFileSync(join(FIXTURES, 'agreement.otj')));
  const header = parseHeader(native);
  const diagnostics = parseDiagnostics(text('agreement.csv'));

  it('is the double-precision build of the same interface', async () => {
    const module = await loadOrrery(BASE);
    expect(module._orrery_scalar_size()).toBe(header.scalar);
    expect(module._orrery_particle_limit()).toBeGreaterThan(0);
    expect(module._orrery_step_limit()).toBeGreaterThan(0);
  });

  it('reaches the state the native run reached', async () => {
    const module = await loadOrrery(BASE);
    const result = integrate(module, configuration, 200);

    expect(result.count).toBe(header.count);
    expect(result.step).toBe(200);
    expect(result.time).toBeCloseTo(0.2, 12);

    // The scheduler and the outputs are the two things the module refuses to
    // do, and it says so rather than doing neither quietly.
    expect(result.solver).toBe('direct');
    expect(result.kernel).toBe('scalar');
    expect(result.report).toContain('serial');
    expect(result.report).toContain('output');

    // The last frame the native run wrote, which is the state after all two
    // hundred steps.
    const last = frameCount(native.byteLength, header) - 1;
    const into = {
      x: new Float32Array(header.count),
      y: new Float32Array(header.count),
      z: new Float32Array(header.count),
    };
    const frame = decodeFrame(native, frameOffset(last, header), header, into);
    expect(frame.step).toBe(200);

    for (let index = 0; index < header.count; index += 1) {
      expect(result.x[index] as number).toBeCloseTo(into.x[index] as number, 6);
      expect(result.y[index] as number).toBeCloseTo(into.y[index] as number, 6);
      expect(result.z[index] as number).toBeCloseTo(into.z[index] as number, 6);
    }

    // Nothing above would catch a position array read out in the wrong order,
    // since every particle would still be somewhere the run reached. This
    // would.
    const spread = Math.max(...[...result.x].map(Math.abs));
    expect(spread).toBeGreaterThan(FLOAT_TOLERANCE);
  });

  it('conserves what the native run conserved', async () => {
    const module = await loadOrrery(BASE);
    const result = integrate(module, configuration, 200);

    const row = diagnostics.samples - 1;
    expect(diagnostics.step[row]).toBe(200);

    const drift = result.measurement[MEASUREMENT.energyDrift] as number;
    const virial = result.measurement[MEASUREMENT.virialRatio] as number;
    const energy = result.measurement[MEASUREMENT.totalEnergy] as number;

    expect(relative(virial, diagnostics.virialRatio[row] as number)).toBeLessThan(
      TOLERANCE,
    );

    // A bound rather than a comparison: the diagnostics reader does not carry
    // the energy column, and what the energy has to be is fixed by the two it
    // does carry, since the virial ratio above is that energy's two halves.
    expect(energy).toBeLessThan(0);

    expect(relative(drift, diagnostics.energyDrift[row] as number)).toBeLessThan(
      DRIFT_TOLERANCE,
    );

    // What the run itself did, which is the figure the agreement above should
    // be read against: the two builds differ by less than a millionth of an
    // energy error that is itself three parts in a thousand million.
    expect(Math.abs(drift)).toBeGreaterThan(1e-9);
    expect(Math.abs(drift)).toBeLessThan(1e-8);
  });
});

/** The difference between two numbers as a fraction of the larger. */
function relative(a: number, b: number): number {
  const scale = Math.max(Math.abs(a), Math.abs(b));
  return scale === 0 ? 0 : Math.abs(a - b) / scale;
}
