"""Write the client's half of the contract from the service's models.

    python service/tools/export_contract.py
    python service/tools/export_contract.py --check

The first writes `web/src/service/contract.ts`. The second writes nothing and
exits non-zero if what is on disk is not what would be written, which is what
continuous integration runs: a field added to `contract.py` and not regenerated
fails there rather than reaching a client that does not know about it.

## Why this and not a schema generator

Pydantic will produce JSON Schema, and there are tools that turn JSON Schema
into TypeScript. Using them would mean two generation steps, a dependency whose
output nobody in this project reads, and a file full of the constructs a general
generator emits for cases this contract does not contain. What is actually
needed is a walk over ten models made of strings, numbers, booleans, lists and
each other, and that is the hundred lines below. ADR-0002's rule about
dependencies applies: every one needs a sentence saying why it beats writing the
code, and this is the case where writing the code wins.

The narrowness is deliberate and is enforced. An annotation this does not
recognise stops the export with a message naming the field, rather than being
rendered as `unknown` and discovered later by somebody reading a client that
compiles and means nothing.
"""

from __future__ import annotations

import argparse
import inspect
import sys
import types
import typing
from pathlib import Path

REPOSITORY = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPOSITORY / "service"))

from pydantic import BaseModel  # noqa: E402

from orrery_service import contract  # noqa: E402

OUTPUT = REPOSITORY / "web" / "src" / "service" / "contract.ts"

#: The named unions written out as their own type, rather than inline wherever
#: they are used. Keyed by the name the TypeScript gets.
ALIASES: dict[str, object] = {"JobState": contract.JobState}

PRIMITIVES: dict[object, str] = {
    str: "string",
    int: "number",
    float: "number",
    bool: "boolean",
}


class UnsupportedAnnotation(TypeError):
    """An annotation the export does not know how to write down."""


def _literal(annotation: object) -> str:
    values = typing.get_args(annotation)
    return " | ".join(f"'{value}'" for value in values)


def typescript_for(annotation: object, where: str) -> str:
    """The TypeScript for one field's annotation.

    `where` names the field, and appears in the message if the annotation is one
    this does not handle.
    """
    for name, alias in ALIASES.items():
        if annotation == alias:
            return name

    if annotation in PRIMITIVES:
        return PRIMITIVES[annotation]

    origin = typing.get_origin(annotation)

    if origin is typing.Literal:
        return _literal(annotation)

    if origin in (typing.Union, types.UnionType):
        parts = [
            "null" if part is type(None) else typescript_for(part, where)
            for part in typing.get_args(annotation)
        ]
        return " | ".join(parts)

    if origin is list:
        (item,) = typing.get_args(annotation)
        return f"readonly {typescript_for(item, where)}[]"

    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return annotation.__name__

    raise UnsupportedAnnotation(
        f"{where} is annotated {annotation!r}, which the contract export does "
        f"not write. Either express the field in the types it does handle, or "
        f"teach service/tools/export_contract.py the new one."
    )


def _comment(text: str | None, indent: str) -> list[str]:
    """A docstring or a field description, as a JSDoc block.

    The prose is carried across rather than dropped so that the generated file
    is as readable as the one it came from. It costs the client nothing: an
    interface is erased at build time, comments and all.
    """
    if not text:
        return []
    lines = [line.rstrip() for line in inspect.cleandoc(text).splitlines()]
    if len(lines) == 1:
        return [f"{indent}/** {lines[0]} */"]
    body = [f"{indent} * {line}".rstrip() for line in lines]
    return [f"{indent}/**", *body, f"{indent} */"]


def _model(model: type[BaseModel]) -> list[str]:
    lines = _comment(model.__doc__, "")
    lines.append(f"export interface {model.__name__} {{")
    hints = typing.get_type_hints(model)
    for name, field in model.model_fields.items():
        where = f"{model.__name__}.{name}"
        rendered = typescript_for(hints[name], where)
        lines.extend(_comment(field.description, "  "))
        lines.append(f"  readonly {name}: {rendered};")
    lines.append("}")
    return lines


HEADER = """/**
 * The service's contract, generated from service/orrery_service/contract.py.
 *
 * Do not edit this file. Change the Pydantic models and run
 *
 *     python service/tools/export_contract.py
 *
 * Continuous integration runs the same command and fails if what it writes
 * differs from what is committed, so the two halves of the boundary cannot
 * describe different things.
 */"""


def render() -> str:
    blocks = [HEADER]

    for name, alias in ALIASES.items():
        blocks.append(f"export type {name} = {_literal(alias)};")

    for model in contract.EXPORTED:
        blocks.append("\n".join(_model(model)))

    return "\n\n".join(blocks) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="write nothing, and fail if the committed file is out of date",
    )
    arguments = parser.parse_args()

    rendered = render()
    existing = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else None

    if arguments.check:
        if existing == rendered:
            return 0
        print(
            f"{OUTPUT.relative_to(REPOSITORY)} is out of date. Run "
            f"python service/tools/export_contract.py and commit the result.",
            file=sys.stderr,
        )
        return 1

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.relative_to(REPOSITORY)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
